kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  namespace: default
  labels:
    app: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: jellyfin-config-volume
              mountPath: /config
            - name: qbittorrent-downloads-volume
              mountPath: /downloads
          env:
            - name: PROWLARR__APP__INSTANCENAME
              value: Prowlarr
      volumes:
        - name: jellyfin-config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: qbittorrent-downloads-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc
