apiVersion: v1
kind: Service
metadata:
  name: jellyfinn
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selector:
    app: jellyfinn
  ports:
    - targetPort: 8096
      port: 8096
