apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: charts/metallb
    repoURL: https://github.com/metallb/metallb.git
    targetRevision: metallb-chart-0.14.5
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
