kind: Deployment
apiVersion: apps/v1
metadata:
  name: unpackerr
  namespace: default
  labels:
    app: unpackerr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      labels:
        app: unpackerr
    spec:
      containers:
        - name: unpackerr
          image: golift/unpackerr
          ports:
            - containerPort: 5656
          volumeMounts:
            - name: unpackerr-config-volume
              mountPath: /config
            - name: qbittorrent-downloads-volume
              mountPath: /downloads
          env:
            - name: UN_SONARR_0_URL
              value: http://sonarr.default:8989
            - name: UN_RADARR_0_URL
              value: http://radarr.default:7878
          envFrom:
            - secretRef:
                name: unpackerr-secret
      volumes:
        - name: unpackerr-config-volume
          persistentVolumeClaim:
            claimName: unpackerr-config
        - name: qbittorrent-downloads-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc
