apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-100"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: unpackerr-secret
  data:
    - secretKey: UN_RADARR_0_API_KEY
      remoteRef:
        key: /servarr
        property: un_radarr_0_api_key
    - secretKey: UN_SONARR_0_API_KEY
      remoteRef:
        key: /servarr
        property: un_sonarr_0_api_key
