apiVersion: v1
kind: Service
metadata:
  name: unpackerr
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selector:
    app: unpackerr
  ports:
    - targetPort: 5656
      port: 5656
