kind: Deployment
apiVersion: apps/v1
metadata:
  name: flaresolverr
  namespace: default
  labels:
    app: flaresolverr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: flaresolverr/flaresolverr
          ports:
            - containerPort: 8191
