apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selector:
    app: flaresolverr
  ports:
    - targetPort: 8191
      port: 8191
