apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: 0.9.5
    helm:
      valuesObject:
        pod:
          extraVolumeMounts:
          extraVolumes:
          env:
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia.postgres-authelia.credentials.postgresql.acid.zalan.do
                  key: password
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia-external
                  key: lldap_password
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: authelia-external
                  key: storage_encryption_key
            - name: AUTHELIA_VAULT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authelia-external
                  key: vault_client_secret
        configMap:
          log:
            level: 'debug'
          disabled: false
          telemetry:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                labels:
                  release: monitor
          default_2fa_method: totp
          theme: 'dark'
          password_reset:
            disable: true
          authentication_backend:
            ldap:
              enabled: true
              implementation: 'custom'
              address: 'ldap://lldap:3890'
              base_dn: 'DC=bhamm-lab,DC=com'
              additional_users_dn: ou=people
              users_filter: "(&({username_attribute}={input})(objectClass=person))"
              additional_groups_dn: ou=groups
              groups_filter: "(member={dn})"
              attributes:
                display_name: displayName
                username: uid
                group_name: cn
                mail: mail
              user: 'uid=authelia,ou=people,DC=bhamm-lab,DC=com'
              password:
                disabled: true
          storage:
            encryption_key:
              disabled: true
            postgres:
              enabled: true
              deploy: false
              address: 'tcp://postgres-authelia:5432'
              timeout: '5 seconds'
              database: 'authelia'
              schema: 'public'
              username: 'authelia'
              password:
                disabled: true
              tls:
                skip_verify: true
          notifier:
            filesystem:
              enabled: true
          access_control:
            default_policy: deny
            rules:
              - domain:
                  - nginx.bhamm-lab.com
                  - traefik.bhamm-lab.com
                policy: two_factor
              - domain: '*.bhamm-lab.com'
                policy: one_factor
          session:
            cookies:
              - subdomain: 'auth'
                domain: 'bhamm-lab.com'
            redis:
              enabled: true
              deploy: true
              host: 'authelia-redis-master'
          identity_providers:
            oidc:
              enabled: false
              # jwks:
              #   - key_id: ''
              #     algorithm: 'RS256'
              #     use: 'sig'
              #     key:
              #       value: |
              #       path: '/secrets/oidc.jwk.RS256.pem'
              #     certificate_chain:
              #       path: '/secrets.oidc.jwk.RS256.crt'
              authorization_policies:
                policy_name:
                  default_policy: 'two_factor'
                  rules:
                    - policy: 'deny'
                      subject: 'group:services'
              clients:
                - client_id: 'vault'
                  client_name: 'HashiCorp Vault'
                  client_secret: '$pbkdf2-sha512$310000$jU2648xjIbQp6u9EKayzHQ$J9wuOiPMpEF9oxNX08bBxWdGLS8YUAfx.ZD26bmtpqOL.mv1yiLVQ/Jw.jBhPFNBwuMZTnkepgdc/d2Q55XolA' # '{{ env "AUTHELIA_VAULT_CLIENT_SECRET" }}'
                  public: false
                  authorization_policy: 'two_factor'
                  redirect_uris:
                    - 'https://vault.bhamm-lab.com/oidc/callback'
                    - 'https://vault.bhamm-lab.com/ui/vault/auth/oidc/oidc/callback'
                  scopes:
                    - 'openid'
                    - 'profile'
                    - 'groups'
                    - 'email'
                  userinfo_signed_response_alg: 'none'
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
