apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: 0.9.5
    helm:
      valuesObject:
        pod:
          extraVolumeMounts:
          extraVolumes:
          env:
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.postgres-authelia.credentials.postgresql.acid.zalan.do
                  key: password
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia-external
                  key: lldap_password
        configMap:
          log:
            level: 'debug'
          disabled: false
          telemetry:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                labels:
                  release: monitor
          theme: 'dark'
          authentication_backend:
            ldap:
              enabled: true
              implementation: 'lldap'
              address: 'ldap://lldap'
              base_dn: 'DC=bhamm-lab,DC=com'
              additional_users_dn: 'OU=Users'
              additional_groups_dn: 'OU=Groups'
              user: 'CN=authelia,DC=bhamm-lab,DC=com'
              password:
                disabled: true
          storage:
            postgres:
              enabled: true
              deploy: false
              address: 'postgres://postgres-authelia:5432'
              timeout: '5 seconds'
              database: 'authelia'
              schema: 'public'
              username: 'authelia'
              password:
                disabled: true
              tls:
                skip_verify: true
          notifier:
            filesystem:
              enabled: true
          session:
            cookies:
              - subdomain: 'auth'
                domain: 'bhamm-lab.com'
            redis:
              enabled: true
              deploy: true
              host: 'authelia-redis-master'
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
