apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-community/kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.1
    # helm:
    #   valuesObject:
    #     globalArguments:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
