apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.2.0
    helm:
      valuesObject:
        # prometheus:
        #   prometheusSpec:
        #     serviceMonitorSelector:
        #       matchLabels:
        #         Release: monitor # Default
        #       matchLabels:
        #         team: rook
        grafana:
          admin:
            existingSecret: monitoring-login
            userKey: admin-user
            passwordKey: admin-password
          dashboards:
            default:
              ceph-cluster:
                gnetId: 2842
                revision: 17
                datasource: Prometheus
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Replace=true # https://github.com/argoproj/argo-cd/issues/8128
    automated:
      prune: true
      selfHeal: true
