apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.2.0
    # helm:
    #   valuesObject:
    #     globalArguments:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
    ignoreDifferences: # https://github.com/argoproj/argo-cd/issues/8128
      - group: monitoring.coreos.com
        kind: ServiceMonitor
        jqPathExpressions:
          - .spec.endpoints[]?.relabelings[]?.action
