apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
