apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selector:
    app: sonarr
  ports:
    - targetPort: 8989
      port: 8989
