apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: default
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "8G"
    requests.cpu: "3"
    requests.memory: "6G"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: default
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "1000M"
      defaultRequest:
        cpu: "250m"
        memory: "500M"
      max:
        cpu: "2"
        memory: "2000M"
      min:
        cpu: "100m"
        memory: "200M"
      type: Container
