apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: bhamm-homelab@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: bhamm-homelab@gmail.com
            apiTokenSecretRef: # Replace with vault
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "bhamm-lab.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bhamm-lab-tls
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: bhamm-lab-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.bhamm-lab.com"
  dnsNames:
    - "bhamm-lab.com"
    - "*.bhamm-lab.com"
