apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  argocd-vault-plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
