apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.1.0
    helm:
      valuesObject:
        redis-ha:
          enabled: true
        controller:
          replicas: 1
        server:
          replicas: 2
        applicationSet:
          replicas: 2
        repoServer:
          replicas: 2
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/argocd-vault-plugin
              subPath: argocd-vault-plugin
          envFrom:
            - secretRef:
              name: argocd-vault-plugin-credentials
          volumes:
            - name: custom-tools
              emptyDir: {}
          initContainers:
            - name: download-tools
              image: alpine:3.8
              command: [sh, -c]
              env:
                - name: AVP_VERSION
                  value: "1.18.0"
              args:
                - >-
                  wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 && chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
        configs:
          params:
            server.insecure: true
          cmp:
            create: true
            plugins:
              argocd-vault-plugin:
                generate:
                  command: ["argocd-vault-plugin"]
                  args: ["generate", "./"]
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
