apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.1.0
    helm:
      valuesObject:
        redis-ha:
          enabled: true
        controller:
          replicas: 2
        server:
          replicas: 2
        applicationSet:
          replicas: 2
        repoServer:
          replicas: 2
          automountServiceAccountToken: true
          volumes:
            - configMap:
                name: cmp-plugin
              name: cmp-plugin
            - name: custom-tools
              emptyDir: {}
          initContainers:
            - name: download-tools
              image: registry.access.redhat.com/ubi8
              env:
                - name: AVP_VERSION
                  value: 1.18.1
              command: [sh, -c]
              args:
                - >-
                  curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin && chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
          extraContainers:
            - name: avp
              command: [/var/run/argocd/argocd-cmp-server]
              image: registry.access.redhat.com/ubi8
              securityContext:
                runAsNonRoot: true
                runAsUser: 999
              volumeMounts:
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /tmp
                  name: tmp
                # Register plugins into sidecar
                - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                  subPath: avp.yaml
                  name: cmp-plugin
                # Important: Mount tools into $PATH
                - name: custom-tools
                  subPath: argocd-vault-plugin
                  mountPath: /usr/local/bin/argocd-vault-plugin
            - name: avp-helm
              command: [/var/run/argocd/argocd-cmp-server]
              args:
                - >-
                  yum -y install kubernetes-helm
              image: registry.access.redhat.com/ubi8
              securityContext:
                runAsNonRoot: true
                runAsUser: 999
              volumeMounts:
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /tmp
                  name: tmp
                # Register plugins into sidecar
                - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                  subPath: avp-helm.yaml
                  name: cmp-plugin
                # Important: Mount tools into $PATH
                - name: custom-tools
                  subPath: argocd-vault-plugin
                  mountPath: /usr/local/bin/argocd-vault-plugin-helm
            - name: avp-kustomize
              command: [/var/run/argocd/argocd-cmp-server]
              image: registry.access.redhat.com/ubi8
              securityContext:
                runAsNonRoot: true
                runAsUser: 999
              volumeMounts:
                - mountPath: /var/run/argocd
                  name: var-files
                - mountPath: /home/argocd/cmp-server/plugins
                  name: plugins
                - mountPath: /tmp
                  name: tmp
                # Register plugins into sidecar
                - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                  subPath: avp-kustomize.yaml
                  name: cmp-plugin
                # Important: Mount tools into $PATH
                - name: custom-tools
                  subPath: argocd-vault-plugin
                  mountPath: /usr/local/bin/argocd-vault-plugin-kustomize
        configs:
          params:
            server.insecure: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
