apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.1.0
    helm:
      valuesObject:
        configs:
          params:
            server.insecure: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
