apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/cmp-configmap
    repoURL: https://github.com/argoproj-labs/argocd-vault-plugin.git
    targetRevision: v1.18.0
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
