apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  labels:
    app: traefik
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v28.0.0
    helm:
      valueFiles:
        - values.yaml
