apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  labels:
    app: traefik
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: v26.0.0
    helm:
      valueFiles:
        - values.yaml
  # syncPolicy:
  #   syncOptions:
  #     - CreateNamespace=true
  #     - ApplyOutOfSyncOnly=true
  #   automated:
  #     prune: true
  #     selfHeal: true
