apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: lan-ips
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "50"
spec:
  ipAllowList:
    sourceRange:
      - 192.168.69.1/24
