apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: framework-ip
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "50"
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.69.40
