globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
deployment:
  enabled: true
  replicas: null
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []
resources:
  requests:
    cpu: "100m"
    memory: "50M"
  limits:
    cpu: "300m"
    memory: "150M"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
ingressRoute:
  dashboard:
    enabled: false
providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false
rbac:
  enabled: true
service:
  enabled: true
  type: LoadBalancer
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: local.bhamm-lab.com
  labels: {}
  loadBalancerSourceRanges: []
  externalIPs: []
