apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      valuesObject:
        storageClass.defaultClass: true
        nfs:
          server: 192.168.69.12
          path: /zpool_ssd/kubernetes
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
