apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-150"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.13.6
    helm:
      valuesObject: # https://github.com/rook/rook/blob/release-1.9/deploy/charts/rook-ceph-cluster/values.yaml
        operatorNamespace: default
        clusterName: rook-ceph
        cephClusterSpec:
          storage:
            useAllNodes: false
            useAllDevices: false
            nodes:
              - name: "precision"
                devices:
                  - name: "/dev/disk/by-id/nvme-SHGP31-1000GM-2_AS0CN42841190CT25"
              - name: "thinkpad"
                devices:
                  - name: "/dev/disk/by-id/nvme-CT1000P3PSSD8_2422492DF9B7"
              - name: "elitebook"
                devices:
                  - name: "/dev/disk/by-id/nvme-CT1000P3PSSD8_2422492E9226"
                    # config:
                    #   osdsPerDevice: "5"
        cephBlockPools:
          - name: ceph-blockpool
            # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md#spec for available configuration
            spec:
              failureDomain: host
              replicated:
                size: 3
            storageClass:
              enabled: true
              name: ceph-block
              isDefault: true
              reclaimPolicy: Delete
              allowVolumeExpansion: true
              mountOptions: []
              # see https://github.com/rook/rook/blob/master/Documentation/ceph-block.md#provision-storage for available configuration
              parameters:
                # (optional) mapOptions is a comma-separated list of map options.
                # For krbd options refer
                # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
                # For nbd options refer
                # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
                # mapOptions: lock_on_read,queue_depth=1024

                # (optional) unmapOptions is a comma-separated list of unmap options.
                # For krbd options refer
                # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
                # For nbd options refer
                # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
                # unmapOptions: force

                # RBD image format. Defaults to "2".
                imageFormat: "2"
                # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
                imageFeatures: layering
                # The secrets contain Ceph admin credentials.
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: default
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: default
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                csi.storage.k8s.io/node-stage-secret-namespace: default
                # Specify the filesystem type of the volume. If not specified, csi-provisioner
                # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
                # in hyperconverged settings where the volume is mounted on the same node as the osds.
                csi.storage.k8s.io/fstype: ext4
        cephFileSystems:
          - name: ceph-filesystem
            # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md#filesystem-settings for available configuration
            spec:
              metadataPool:
                replicated:
                  size: 3
              dataPools:
                - failureDomain: host
                  replicated:
                    size: 3
                  # Optional and highly recommended, 'data0' by default, see https://github.com/rook/rook/blob/master/Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md#pools
                  name: data0
              metadataServer:
                activeCount: 1
                activeStandby: true
                priorityClassName: system-cluster-critical
            storageClass:
              enabled: true
              isDefault: false
              name: ceph-filesystem
              # (Optional) specify a data pool to use, must be the name of one of the data pools above, 'data0' by default
              pool: data0
              reclaimPolicy: Delete
              allowVolumeExpansion: true
              mountOptions: []
              # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage for available configuration
              parameters:
                # The secrets contain Ceph admin credentials.
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: default
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: default
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
                csi.storage.k8s.io/node-stage-secret-namespace: default
                # Specify the filesystem type of the volume. If not specified, csi-provisioner
                # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
                # in hyperconverged settings where the volume is mounted on the same node as the osds.
                csi.storage.k8s.io/fstype: ext4
        cephFileSystemVolumeSnapshotClass:
          enabled: false
          name: ceph-filesystem
          isDefault: true
          deletionPolicy: Delete
          annotations: {}
          labels: {}
          # see https://rook.io/docs/rook/latest/ceph-csi-snapshot.html#cephfs-snapshots for available configuration
          parameters: {}
        cephBlockPoolsVolumeSnapshotClass:
          enabled: false
          name: ceph-block
          isDefault: false
          deletionPolicy: Delete
          annotations: {}
          labels: {}
          # see https://rook.io/docs/rook/latest/ceph-csi-snapshot.html#rbd-snapshots for available configuration
          parameters: {}
        cephObjectStores:
          - name: ceph-objectstore
            # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Object-Storage/ceph-object-store-crd.md#object-store-settings for available configuration
            spec:
              metadataPool:
                failureDomain: host
                replicated:
                  size: 3
              dataPool:
                failureDomain: host
                erasureCoded:
                  dataChunks: 2
                  codingChunks: 1
              preservePoolsOnDelete: true
              gateway:
                port: 80
                # securePort: 443
                # sslCertificateRef:
                instances: 1
                priorityClassName: system-cluster-critical
            storageClass:
              enabled: true
              name: ceph-bucket
              reclaimPolicy: Delete
              # see https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#storageclass for available configuration
              parameters:
                # note: objectStoreNamespace and objectStoreName are configured by the chart
                region: us-east-1
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
