kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorent
  namespace: default
  labels:
    app: qbittorent
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorent
  template:
    metadata:
      labels:
        app: qbittorent
    spec:
      containers:
        - name: qbittorent
          image: lscr.io/linuxserver/qbittorent:latest
          volumeMounts:
            - name: qbittorent-config-volume
              mountPath: /config
            - name: qbittorent-downloads-volume
              mountPath: /downloads
      volumes:
        - name: qbittorent-config-volume
          persistentVolumeClaim:
            claimName: qbittorent-config-pvc
        - name: qbittorent-downloads-volume
          persistentVolumeClaim:
            claimName: qbittorent-downloads-pvc
