kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
  namespace: default
  labels:
    app: qbittorrent
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          volumeMounts:
            - name: qbittorrent-config-volume
              mountPath: /config
            - name: qbittorrent-downloads-volume
              mountPath: /downloads
        - name: gluetun
          image: qmcgaw/gluetun:latest
          env:
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_INTERFACE
              value: wg0
            - name: VPN_ENDPOINT_PORT
              value: "51820"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: protonvpn
          envFrom:
            - secretRef:
                name: qbittorrent-secret
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            allowPrivilegeEscalation: false
      volumes:
        - name: qbittorrent-config-volume
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-downloads-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc
