apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-100"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: qbittorrent-secret
  data:
    - secretKey: VPN_ENDPOINT_IP
      remoteRef:
        key: /protonvpn
        property: qbittorrent_vpn_endpoint_ip
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: /protonvpn
        property: qbittorrent_wireguard_public_key
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: /protonvpn
        property: qbittorrent_wireguard_private_key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: /protonvpn
        property: qbittorrent_wireguard_addresses
