apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: "secret/data/ldap"
    argocd.argoproj.io/sync-wave: "-50"
type: Opaque
stringData:
  ADMIN_PASSWORD: <ADMIN_PASSWORD>
