apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: default
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    avp.kubernetes.io/path: "secret/data/ldap"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: openldap-stack-ha
    repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.2.4
    helm:
      valuesObject:
        global:
          ldapDomain: "bhamm-lab.com"
          adminPassword: <ADMIN_PASSWORD>
          configPassword: <ADMIN_PASSWORD>
        ltb-passwd:
          enabled: true
          ingress:
            enabled: false
        phpldapadmin:
          enabled: true
          ingress:
            enabled: false
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
