apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: default
  labels:
    app.kubernetes.io/name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: openldap-stack-ha
    repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.2.4
    helm:
      valuesObject:
        global:
          ldapDomain: "bhamm-lab.com"
          adminPassword: vault:secret/ldap#ADMIN_PASSWORD
          configPassword: vault:secret/ldap#ADMIN_PASSWORD
        ltb-passwd:
          enabled: true
          ingress:
            enabled: false
        phpldapadmin:
          enabled: true
          ingress:
            enabled: false
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
