apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: openldap-stack-ha
    repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.2.4
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
