apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  annotations:
    avp.kubernetes.io/path: "secret/data/ldap"
    argocd.argoproj.io/sync-wave: "-50"
stringData:
  # vault:secret/data/ldap#ADMIN_PASSWORD
  LDAP_ADMIN_PASSWORD: <ADMIN_PASSWORD>
  LDAP_CONFIG_ADMIN_PASSWORD: <ADMIN_PASSWORD>
type: Opaque
