apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  labels:
    avp.kubernetes.io/path: "secret/data/ldap"
data:
  # vault:secret/data/ldap#ADMIN_PASSWORD
  LDAP_ADMIN_PASSWORD: <ADMIN_PASSWORD>
  LDAP_CONFIG_ADMIN_PASSWORD: <ADMIN_PASSWORD>
type: Opaque
