apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  labels:
    app.kubernetes.io/name: vault
  annotations:
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
data:
  # vault:secret/data/ldap#ADMIN_PASSWORD
  LDAP_ADMIN_PASSWORD: ${vault:secret/data/ldap#ADMIN_PASSWORD}
  LDAP_CONFIG_ADMIN_PASSWORD: ${vault:secret/data/ldap#ADMIN_PASSWORD}
type: Opaque
