apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  labels:
    app.kubernetes.io/name: vault
  annotations:
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
data:
  # vault:secret/data/ldap#ADMIN_PASSWORD
  LDAP_ADMIN_PASSWORD: dmF1bHQ6c2VjcmV0L2RhdGEvbGRhcCNBRE1JTl9QQVNTV09SRA==
  LDAP_CONFIG_ADMIN_PASSWORD: dmF1bHQ6c2VjcmV0L2RhdGEvbGRhcCNBRE1JTl9QQVNTV09SRA==
type: Opaque
