apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vault-operator
    repoURL: ghcr.io/bank-vaults/helm-charts
    targetRevision: 1.22.1
    helm:
      valuesObject:
        replicaCount: 2
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
