apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-rbac
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/rbac
    repoURL: https://github.com/bank-vaults/vault-operator.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
