apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-webhook
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vault-secrets-webhook
    repoURL: ghcr.io/bank-vaults/helm-charts
    targetRevision: 1.21.1
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
