apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-test
  annotations:
    avp.kubernetes.io/path: "secret/data/demosecret/aws"
type: Opaque
stringData:
  # AVP NOT WORKING
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY_INLINE: <path:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY>
