apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selector:
    app: prowlarr
  ports:
    - targetPort: 9696
      port: 9696
