apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  labels:
    app: cert-manager
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.3
    helm:
      valuesObject:
        installCRDs: true
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
          - --dns01-recursive-nameservers-only
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - 1.1.1.1
            - 1.0.0.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
